name: Test HTML Básico

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Listar archivos
        run: ls -R

      - name: Mostrar contenido del index.html
        run: cat index.html
